

package com.mangy.cube;

import com.mangy.game.Main;
import com.mangy.vbo.Texture;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;


public class Level_1{

    Main main;
    Cube cub;
    
    Texture  steel_texture;
    Texture  brick_texture; 
    
            
    public Level_1(Main main) throws FileNotFoundException {
       this.main = main;
       
       steel_texture = new Texture(new FileInputStream(new File("Textures/cube/steel.png")));
       brick_texture = new Texture(new FileInputStream(new File("Textures/cube/brick.png")));
    }
    
    public void loadLevel() throws FileNotFoundException {
    
      
      cub = new Cube(steel_texture, "steel");
      cub.X =  0.25f;
      cub.Y =  0.25f;
      cub.Z =  0.1f;
      main.gamePlayers.getListaCubes().add(cub);
      cub = new Cube(steel_texture, "steel");
      cub.X = 0.25f;
      cub.Y = -0.25f;
      cub.Z = 0.1f;
      main.gamePlayers.getListaCubes().add(cub);    
      cub = new Cube(steel_texture, "steel");
      cub.X = 0.75f;
      cub.Y = -0.25f;
      cub.Z = 0.1f;
      main.gamePlayers.getListaCubes().add(cub);       
      cub = new Cube(steel_texture , "steel");
      cub.X = 0.75f;
      cub.Y = 0.25f;
      cub.Z = 0.1f;
      main.gamePlayers.getListaCubes().add(cub);        
     
      main.gamePlayers.getListaCubes().add(cub);       
      cub = new Cube(brick_texture , "brick");
      cub.X = 4.75f;
      cub.Y = -0.75f;
      cub.Z = 0.1f;
      main.gamePlayers.getListaCubes().add(cub);
      main.gamePlayers.getListaCubes().add(cub);       
      cub = new Cube(brick_texture, "brick");
      cub.X = 4.25f;
      cub.Y = -0.75f;
      cub.Z = 0.1f;
      main.gamePlayers.getListaCubes().add(cub);        
      cub = new Cube(brick_texture , "brick");
      cub.X = 3.75f;
      cub.Y = -0.75f;
      cub.Z = 0.1f;
      main.gamePlayers.getListaCubes().add(cub);    
      cub = new Cube(brick_texture , "brick");
      cub.X = 3.75f;
      cub.Y = -0.25f;
      cub.Z = 0.1f;
      main.gamePlayers.getListaCubes().add(cub);        
      cub = new Cube(brick_texture , "brick");
      cub.X = 3.75f;
      cub.Y = 0.25f;
      cub.Z = 0.1f;
      main.gamePlayers.getListaCubes().add(cub);        
      cub = new Cube(brick_texture , "brick");
      cub.X = 3.75f;
      cub.Y = 0.75f;
      cub.Z = 0.1f;
      main.gamePlayers.getListaCubes().add(cub);  
      cub = new Cube(brick_texture , "brick");
      cub.X = 4.25f;
      cub.Y = 0.75f;
      cub.Z = 0.1f;
      main.gamePlayers.getListaCubes().add(cub);          
      cub = new Cube(brick_texture , "brick");
      cub.X = 4.75f;
      cub.Y = 0.75f;
      cub.Z = 0.1f;
      main.gamePlayers.getListaCubes().add(cub); 
      
      cub = new Cube(brick_texture , "brick");
      cub.X = 3.75f;
      cub.Y = -1.75f;
      cub.Z = 0.1f;
      main.gamePlayers.getListaCubes().add(cub); 
      cub = new Cube(brick_texture , "brick");
      cub.X = 3.25f;
      cub.Y = -1.75f;
      cub.Z = 0.1f;
      main.gamePlayers.getListaCubes().add(cub);      
      cub = new Cube(brick_texture , "brick");
      cub.X = 2.75f;
      cub.Y = -1.75f;
      cub.Z = 0.1f;
      main.gamePlayers.getListaCubes().add(cub);
      cub = new Cube(brick_texture , "brick");
      cub.X = 2.25f;
      cub.Y = -1.75f;
      cub.Z = 0.1f;
      main.gamePlayers.getListaCubes().add(cub);  
      cub = new Cube(brick_texture , "brick");
      cub.X = 1.75f;
      cub.Y = -1.75f;
      cub.Z = 0.1f;
      main.gamePlayers.getListaCubes().add(cub); 
      cub = new Cube(brick_texture , "brick");
      cub.X = 1.75f;
      cub.Y = -2.25f;
      cub.Z = 0.1f;
      main.gamePlayers.getListaCubes().add(cub);      
      cub = new Cube(brick_texture , "brick");
      cub.X = 2.25f;
      cub.Y = -2.25f;
      cub.Z = 0.1f;
      main.gamePlayers.getListaCubes().add(cub);        
      main.gamePlayers.getListaCubes().add(cub);      
      cub = new Cube(brick_texture , "brick");
      cub.X = 2.75f;
      cub.Y = -2.25f;
      cub.Z = 0.1f;
      main.gamePlayers.getListaCubes().add(cub);  
      cub = new Cube(brick_texture , "brick");
      cub.X = 3.25f;
      cub.Y = -2.25f;
      cub.Z = 0.1f;
      main.gamePlayers.getListaCubes().add(cub);        
      cub = new Cube(brick_texture , "brick");
      cub.X = 3.75f;
      cub.Y = -2.25f;
      cub.Z = 0.1f;
      main.gamePlayers.getListaCubes().add(cub);      
      
      cub = new Cube(brick_texture , "brick");
      cub.X = 1.25f;
      cub.Y = -0.75f;
      cub.Z = 0.1f;
      main.gamePlayers.getListaCubes().add(cub); 
      cub = new Cube(brick_texture , "brick");
      cub.X = 0.75f;
      cub.Y = -0.75f;
      cub.Z = 0.1f;
      main.gamePlayers.getListaCubes().add(cub);       
      cub = new Cube(brick_texture , "brick");
      cub.X = 0.25f;
      cub.Y = -0.75f;
      cub.Z = 0.1f;
      main.gamePlayers.getListaCubes().add(cub);     
      cub = new Cube(brick_texture , "brick");
      cub.X = -0.25f;
      cub.Y = -0.75f;
      cub.Z = 0.1f;
      main.gamePlayers.getListaCubes().add(cub); 
      cub = new Cube(brick_texture , "brick");
      cub.X = 1.25f;
      cub.Y = 0.75f;
      cub.Z = 0.1f;
      main.gamePlayers.getListaCubes().add(cub);        
      cub = new Cube(brick_texture , "brick");
      cub.X = 0.75f;
      cub.Y = 0.75f;
      cub.Z = 0.1f;
      main.gamePlayers.getListaCubes().add(cub);  
      cub = new Cube(brick_texture , "brick");
      cub.X = 0.25f;
      cub.Y = 0.75f;
      cub.Z = 0.1f;
      main.gamePlayers.getListaCubes().add(cub);        
      cub = new Cube(brick_texture, "brick");
      cub.X = -0.25f;
      cub.Y = 0.75f;
      cub.Z = 0.1f;
      main.gamePlayers.getListaCubes().add(cub);       
      cub = new Cube(brick_texture , "brick");
      cub.X = 3.75f;
      cub.Y = -3.25f;
      cub.Z = 0.1f;
      main.gamePlayers.getListaCubes().add(cub);       
      cub = new Cube(brick_texture , "brick");
      cub.X = 3.25f;
      cub.Y = -3.25f;
      cub.Z = 0.1f;
      main.gamePlayers.getListaCubes().add(cub);    
      cub = new Cube(brick_texture , "brick");
      cub.X = 2.75f;
      cub.Y = -3.25f;
      cub.Z = 0.1f;
      main.gamePlayers.getListaCubes().add(cub);          
      cub = new Cube(brick_texture , "brick");
      cub.X = 2.25f;
      cub.Y = -3.25f;
      cub.Z = 0.1f;
      main.gamePlayers.getListaCubes().add(cub); 
      cub = new Cube(brick_texture , "brick");
      cub.X = 1.75f;
      cub.Y = -3.25f;
      cub.Z = 0.1f;
      main.gamePlayers.getListaCubes().add(cub);       
      cub = new Cube(brick_texture , "brick");
      cub.X = 1.75f;
      cub.Y = -3.75f;
      cub.Z = 0.1f;
      main.gamePlayers.getListaCubes().add(cub);        
      cub = new Cube(brick_texture , "brick");
      cub.X = 2.25f;
      cub.Y = -3.75f;
      cub.Z = 0.1f;
      main.gamePlayers.getListaCubes().add(cub); 
      cub = new Cube(brick_texture , "brick");
      cub.X = 2.75f;
      cub.Y = -3.75f;
      cub.Z = 0.1f;
      main.gamePlayers.getListaCubes().add(cub);       
      cub = new Cube(brick_texture , "brick");
      cub.X = 3.25f;
      cub.Y = -3.75f;
      cub.Z = 0.1f;
      main.gamePlayers.getListaCubes().add(cub);  
      cub = new Cube(brick_texture , "brick");
      cub.X = 3.75f;
      cub.Y = -3.75f;
      cub.Z = 0.1f;
      main.gamePlayers.getListaCubes().add(cub);        
      cub = new Cube(brick_texture , "brick");
      cub.X = 3.75f;
      cub.Y = 1.75f;
      cub.Z = 0.1f;
      main.gamePlayers.getListaCubes().add(cub);         
      cub = new Cube(brick_texture , "brick");
      cub.X = 3.25f;
      cub.Y = 1.75f;
      cub.Z = 0.1f;
      main.gamePlayers.getListaCubes().add(cub);       
      cub = new Cube(brick_texture , "brick");
      cub.X = 2.75f;
      cub.Y = 1.75f;
      cub.Z = 0.1f;
      main.gamePlayers.getListaCubes().add(cub);       
      cub = new Cube(brick_texture , "brick");
      cub.X = 2.25f;
      cub.Y = 1.75f;
      cub.Z = 0.1f;
      main.gamePlayers.getListaCubes().add(cub);        
      cub = new Cube(brick_texture , "brick");
      cub.X = 1.75f;
      cub.Y = 1.75f;
      cub.Z = 0.1f;
      main.gamePlayers.getListaCubes().add(cub); 
      cub = new Cube(brick_texture , "brick");
      cub.X = 1.75f;
      cub.Y = 2.25f;
      cub.Z = 0.1f;
      main.gamePlayers.getListaCubes().add(cub);       
      cub = new Cube(brick_texture, "brick");
      cub.X = 2.25f;
      cub.Y = 2.25f;
      cub.Z = 0.1f;
      main.gamePlayers.getListaCubes().add(cub);        
      cub = new Cube(brick_texture , "brick");
      cub.X = 2.75f;
      cub.Y = 2.25f;
      cub.Z = 0.1f;
      main.gamePlayers.getListaCubes().add(cub);       
      cub = new Cube(brick_texture , "brick");
      cub.X = 3.25f;
      cub.Y = 2.25f;
      cub.Z = 0.1f;
      main.gamePlayers.getListaCubes().add(cub);       
      cub = new Cube(brick_texture , "brick");
      cub.X = 3.75f;
      cub.Y = 2.25f;
      cub.Z = 0.1f;
      main.gamePlayers.getListaCubes().add(cub);          
      cub = new Cube(brick_texture , "brick");
      cub.X = 3.75f;
      cub.Y = 3.25f;
      cub.Z = 0.1f;
      main.gamePlayers.getListaCubes().add(cub);        
      cub = new Cube(brick_texture , "brick");
      cub.X = 3.25f;
      cub.Y = 3.25f;
      cub.Z = 0.1f;
      main.gamePlayers.getListaCubes().add(cub);          
      cub = new Cube(brick_texture , "brick");
      cub.X = 2.75f;
      cub.Y = 3.25f;
      cub.Z = 0.1f;
      main.gamePlayers.getListaCubes().add(cub);         
      cub = new Cube(brick_texture , "brick");
      cub.X = 2.25f;
      cub.Y = 3.25f;
      cub.Z = 0.1f;
      main.gamePlayers.getListaCubes().add(cub);       
      cub = new Cube(brick_texture , "brick");
      cub.X = 1.75f;
      cub.Y = 3.25f;
      cub.Z = 0.1f;
      main.gamePlayers.getListaCubes().add(cub);         
      cub = new Cube(brick_texture , "brick");
      cub.X = 1.75f;
      cub.Y = 3.75f;
      cub.Z = 0.1f;
      main.gamePlayers.getListaCubes().add(cub);        
      cub = new Cube(brick_texture , "brick");
      cub.X = 2.25f;
      cub.Y = 3.75f;
      cub.Z = 0.1f;
      main.gamePlayers.getListaCubes().add(cub);        
      cub = new Cube(brick_texture , "brick");
      cub.X = 2.75f;
      cub.Y = 3.75f;
      cub.Z = 0.1f;
      main.gamePlayers.getListaCubes().add(cub);      
      cub = new Cube(brick_texture , "brick");
      cub.X = 3.25f;
      cub.Y = 3.75f;
      cub.Z = 0.1f;
      main.gamePlayers.getListaCubes().add(cub);       
      cub = new Cube(brick_texture , "brick");
      cub.X = 3.75f;
      cub.Y = 3.75f;
      cub.Z = 0.1f;
      main.gamePlayers.getListaCubes().add(cub);   
      cub = new Cube(brick_texture , "brick");
      cub.X = 0.75f;
      cub.Y = -2.75f;
      cub.Z = 0.1f;
      main.gamePlayers.getListaCubes().add(cub);         
      cub = new Cube(brick_texture  , "brick");
      cub.X = 0.25f;
      cub.Y = -2.75f;
      cub.Z = 0.1f;
      main.gamePlayers.getListaCubes().add(cub);        
      cub = new Cube(brick_texture , "brick");
      cub.X = -0.25f;
      cub.Y = -2.75f;
      cub.Z = 0.1f;
      main.gamePlayers.getListaCubes().add(cub);        
      cub = new Cube(brick_texture , "brick");
      cub.X = -0.25f;
      cub.Y = -3.25f;
      cub.Z = 0.1f;
      main.gamePlayers.getListaCubes().add(cub);     
      cub = new Cube(brick_texture , "brick");
      cub.X = 0.25f;
      cub.Y = -3.25f;
      cub.Z = 0.1f;
      main.gamePlayers.getListaCubes().add(cub);        
      cub = new Cube(brick_texture , "brick");
      cub.X = 0.75f;
      cub.Y = -3.25f;
      cub.Z = 0.1f;
      main.gamePlayers.getListaCubes().add(cub);      
      main.gamePlayers.getListaCubes().add(cub);        
      cub = new Cube(brick_texture , "brick");
      cub.X = 0.75f;
      cub.Y = -3.75f;
      cub.Z = 0.1f;
      main.gamePlayers.getListaCubes().add(cub);      
      cub = new Cube(brick_texture , "brick");
      cub.X = 0.25f;
      cub.Y = -3.75f;
      cub.Z = 0.1f;
      main.gamePlayers.getListaCubes().add(cub);        
      cub = new Cube(brick_texture , "brick");
      cub.X = -0.25f;
      cub.Y = -3.75f;
      cub.Z = 0.1f;
      main.gamePlayers.getListaCubes().add(cub);          
      cub = new Cube(brick_texture , "brick");
      cub.X = -0.25f;
      cub.Y = -4.25f;
      cub.Z = 0.1f;
      main.gamePlayers.getListaCubes().add(cub);   
      cub = new Cube(brick_texture , "brick");
      cub.X = 0.25f;
      cub.Y = -4.25f;
      cub.Z = 0.1f;
      main.gamePlayers.getListaCubes().add(cub); 
      cub = new Cube(brick_texture , "brick");
      cub.X = 0.75f;
      cub.Y = -4.25f;
      cub.Z = 0.1f;
      main.gamePlayers.getListaCubes().add(cub);       
      cub = new Cube(brick_texture , "brick");
      cub.X = 0.75f;
      cub.Y = -4.75f;
      cub.Z = 0.1f;
      main.gamePlayers.getListaCubes().add(cub);        
      cub = new Cube(brick_texture , "brick");
      cub.X = 0.25f;
      cub.Y = -4.75f;
      cub.Z = 0.1f;
      main.gamePlayers.getListaCubes().add(cub);        
      cub = new Cube(brick_texture , "brick");
      cub.X = -0.25f;
      cub.Y = -4.75f;
      cub.Z = 0.1f;
      main.gamePlayers.getListaCubes().add(cub);       
      main.gamePlayers.getListaCubes().add(cub);        
      cub = new Cube(brick_texture , "brick");
      cub.X = 0.75f;
      cub.Y = 2.75f;
      cub.Z = 0.1f;
      main.gamePlayers.getListaCubes().add(cub);  
      cub = new Cube(brick_texture , "brick");
      cub.X = 0.25f;
      cub.Y = 2.75f;
      cub.Z = 0.1f;
      main.gamePlayers.getListaCubes().add(cub);        
      cub = new Cube(brick_texture , "brick");
      cub.X = -0.25f;
      cub.Y = 2.75f;
      cub.Z = 0.1f;
      main.gamePlayers.getListaCubes().add(cub);        
      main.gamePlayers.getListaCubes().add(cub);        
      cub = new Cube(brick_texture , "brick");
      cub.X = -0.25f;
      cub.Y = 3.25f;
      cub.Z = 0.1f;
      main.gamePlayers.getListaCubes().add(cub);  
      cub = new Cube(brick_texture , "brick");
      cub.X = 0.25f;
      cub.Y = 3.25f;
      cub.Z = 0.1f;
      main.gamePlayers.getListaCubes().add(cub);       
      cub = new Cube(brick_texture , "brick");
      cub.X = 0.75f;
      cub.Y = 3.25f;
      cub.Z = 0.1f;
      main.gamePlayers.getListaCubes().add(cub);      
      cub = new Cube(brick_texture , "brick");
      cub.X = 0.75f;
      cub.Y = 3.75f;
      cub.Z = 0.1f;
      main.gamePlayers.getListaCubes().add(cub);       
      cub = new Cube(brick_texture , "brick");
      cub.X = 0.25f;
      cub.Y = 3.75f;
      cub.Z = 0.1f;
      main.gamePlayers.getListaCubes().add(cub);        
      cub = new Cube(brick_texture , "brick");
      cub.X = -0.25f;
      cub.Y = 3.75f;
      cub.Z = 0.1f;
      main.gamePlayers.getListaCubes().add(cub);       
      cub = new Cube(brick_texture , "brick");
      cub.X = -0.25f;
      cub.Y = 4.25f;
      cub.Z = 0.1f;
      main.gamePlayers.getListaCubes().add(cub);  
      cub = new Cube(brick_texture , "brick");
      cub.X = 0.25f;
      cub.Y = 4.25f;
      cub.Z = 0.1f;
      main.gamePlayers.getListaCubes().add(cub);       
      cub = new Cube(brick_texture , "brick");
      cub.X = 0.75f;
      cub.Y = 4.25f;
      cub.Z = 0.1f;
      main.gamePlayers.getListaCubes().add(cub);  
      cub = new Cube(brick_texture , "brick");
      cub.X = 0.75f;
      cub.Y = 4.75f;
      cub.Z = 0.1f;
      main.gamePlayers.getListaCubes().add(cub);  
      cub = new Cube(brick_texture , "brick");
      cub.X = 0.25f;
      cub.Y = 4.75f;
      cub.Z = 0.1f;
      main.gamePlayers.getListaCubes().add(cub);   
      cub = new Cube(brick_texture , "brick");
      cub.X = -0.25f;
      cub.Y = 4.75f;
      cub.Z = 0.1f;
      main.gamePlayers.getListaCubes().add(cub);        
      cub = new Cube(brick_texture , "brick");
      cub.X = -1.25f;
      cub.Y = -3.75f;
      cub.Z = 0.1f;
      main.gamePlayers.getListaCubes().add(cub);  
      cub = new Cube(brick_texture , "brick");
      cub.X = -1.75f;
      cub.Y = -3.75f;
      cub.Z = 0.1f;
      main.gamePlayers.getListaCubes().add(cub);        
      cub = new Cube(brick_texture , "brick");
      cub.X = -2.25f;
      cub.Y = -3.75f;
      cub.Z = 0.1f;
      main.gamePlayers.getListaCubes().add(cub);     
      cub = new Cube(brick_texture , "brick");
      cub.X = -2.75f;
      cub.Y = -3.75f;
      cub.Z = 0.1f;
      main.gamePlayers.getListaCubes().add(cub);         
      cub = new Cube(brick_texture , "brick");
      cub.X = -3.25f;
      cub.Y = -3.75f;
      cub.Z = 0.1f;
      main.gamePlayers.getListaCubes().add(cub);        
      cub = new Cube(brick_texture , "brick");
      cub.X = -3.75f;
      cub.Y = -3.75f;
      cub.Z = 0.1f;
      main.gamePlayers.getListaCubes().add(cub);       
      cub = new Cube(brick_texture , "brick");
      cub.X = -3.25f;
      cub.Y = -3.25f;
      cub.Z = 0.1f;
      main.gamePlayers.getListaCubes().add(cub);        
      cub = new Cube(brick_texture , "brick");
      cub.X = -2.75f;
      cub.Y = -3.25f;
      cub.Z = 0.1f;
      main.gamePlayers.getListaCubes().add(cub);           
      cub = new Cube(brick_texture , "brick");
      cub.X = -2.25f;
      cub.Y = -3.25f;
      cub.Z = 0.1f;
      main.gamePlayers.getListaCubes().add(cub);        
      cub = new Cube(brick_texture , "brick");
      cub.X = -1.75f;
      cub.Y = -3.25f;
      cub.Z = 0.1f;
      main.gamePlayers.getListaCubes().add(cub);        
      main.gamePlayers.getListaCubes().add(cub);        
      cub = new Cube(brick_texture , "brick");
      cub.X = -1.25f;
      cub.Y = -3.25f;
      cub.Z = 0.1f;
      main.gamePlayers.getListaCubes().add(cub);          
      cub = new Cube(brick_texture , "brick");
      cub.X = -3.75f;
      cub.Y = -3.25f;
      cub.Z = 0.1f;
      main.gamePlayers.getListaCubes().add(cub);       
      cub = new Cube(brick_texture , "brick");
      cub.X = -1.25f;
      cub.Y = -2.25f;
      cub.Z = 0.1f;
      main.gamePlayers.getListaCubes().add(cub);        
      cub = new Cube(brick_texture , "brick");
      cub.X = -1.75f;
      cub.Y = -2.25f;
      cub.Z = 0.1f;
      main.gamePlayers.getListaCubes().add(cub);        
      cub = new Cube(brick_texture , "brick");
      cub.X = -2.25f;
      cub.Y = -2.25f;
      cub.Z = 0.1f;
      main.gamePlayers.getListaCubes().add(cub);        
      cub = new Cube(brick_texture , "brick");
      cub.X = -2.75f;
      cub.Y = -2.25f;
      cub.Z = 0.1f;
      main.gamePlayers.getListaCubes().add(cub);        
      cub = new Cube(brick_texture , "brick");
      cub.X = -3.25f;
      cub.Y = -2.25f;
      cub.Z = 0.1f;
      main.gamePlayers.getListaCubes().add(cub);         
      cub = new Cube(brick_texture , "brick");
      cub.X = -3.75f;
      cub.Y = -2.25f;
      cub.Z = 0.1f;
      main.gamePlayers.getListaCubes().add(cub);         
      cub = new Cube(brick_texture , "brick");
      cub.X = -3.75f;
      cub.Y = -1.75f;
      cub.Z = 0.1f;
      main.gamePlayers.getListaCubes().add(cub);        
      cub = new Cube(brick_texture , "brick");
      cub.X = -3.25f;
      cub.Y = -1.75f;
      cub.Z = 0.1f;
      main.gamePlayers.getListaCubes().add(cub); 
      cub = new Cube(brick_texture , "brick");
      cub.X = -2.75f;
      cub.Y = -1.75f;
      cub.Z = 0.1f;
      main.gamePlayers.getListaCubes().add(cub);       
      cub = new Cube(brick_texture , "brick");
      cub.X = -2.25f;
      cub.Y = -1.75f;
      cub.Z = 0.1f;
      main.gamePlayers.getListaCubes().add(cub);       
      cub = new Cube(brick_texture , "brick");
      cub.X = -1.75f;
      cub.Y = -1.75f;
      cub.Z = 0.1f;
      main.gamePlayers.getListaCubes().add(cub);        
      cub = new Cube(brick_texture , "brick");
      cub.X = -1.25f;
      cub.Y = -1.75f;
      cub.Z = 0.1f;
      main.gamePlayers.getListaCubes().add(cub);         
      cub = new Cube(brick_texture , "brick");
      cub.X = -1.25f;
      cub.Y = -0.75f;
      cub.Z = 0.1f;
      main.gamePlayers.getListaCubes().add(cub);        
      cub = new Cube(brick_texture , "brick");
      cub.X = -1.75f;
      cub.Y = -0.75f;
      cub.Z = 0.1f;
      main.gamePlayers.getListaCubes().add(cub);          
      cub = new Cube(brick_texture , "brick");
      cub.X = -2.25f;
      cub.Y = -0.75f;
      cub.Z = 0.1f;
      main.gamePlayers.getListaCubes().add(cub);         
      cub = new Cube(brick_texture , "brick");
      cub.X = -2.75f;
      cub.Y = -0.75f;
      cub.Z = 0.1f;
      main.gamePlayers.getListaCubes().add(cub);      
      cub = new Cube(brick_texture , "brick");
      cub.X = -3.25f;
      cub.Y = -0.75f;
      cub.Z = 0.1f;
      main.gamePlayers.getListaCubes().add(cub);         
      cub = new Cube(brick_texture , "brick");
      cub.X = -3.75f;
      cub.Y = -0.75f;
      cub.Z = 0.1f;
      main.gamePlayers.getListaCubes().add(cub);    
      cub = new Cube(steel_texture , "steel");
      cub.X = -2.25f;
      cub.Y = -0.25f;
      cub.Z = 0.1f;
      main.gamePlayers.getListaCubes().add(cub);         
      cub = new Cube(steel_texture , "steel");
      cub.X = -2.75f;
      cub.Y = -0.25f;
      cub.Z = 0.1f;
      main.gamePlayers.getListaCubes().add(cub);          
      cub = new Cube(steel_texture , "steel");
      cub.X = -2.75f;
      cub.Y = 0.25f;
      cub.Z = 0.1f;
      main.gamePlayers.getListaCubes().add(cub);  
      cub = new Cube(steel_texture , "steel");
      cub.X = -2.25f;
      cub.Y = 0.25f;
      cub.Z = 0.1f;
      main.gamePlayers.getListaCubes().add(cub); 
            
      cub = new Cube(brick_texture , "brick");
      cub.X = -1.25f;
      cub.Y = 0.75f;
      cub.Z = 0.1f;
      main.gamePlayers.getListaCubes().add(cub); 
  
      cub = new Cube(brick_texture , "brick");
      cub.X = -1.75f;
      cub.Y = 0.75f;
      cub.Z = 0.1f;
    
      main.gamePlayers.getListaCubes().add(cub);           
      cub = new Cube(brick_texture , "brick");
      cub.X = -2.25f;
      cub.Y = 0.75f;
      cub.Z = 0.1f;
      main.gamePlayers.getListaCubes().add(cub);        
      cub = new Cube(brick_texture , "brick");
      cub.X = -2.75f;
      cub.Y = 0.75f;
      cub.Z = 0.1f;
      main.gamePlayers.getListaCubes().add(cub);        
      cub = new Cube(brick_texture , "brick");
      cub.X = -3.25f;
      cub.Y = 0.75f;
      cub.Z = 0.1f;
      main.gamePlayers.getListaCubes().add(cub);       
      cub = new Cube(brick_texture , "brick");
      cub.X = -3.75f;
      cub.Y = 0.75f;
      cub.Z = 0.1f;
      main.gamePlayers.getListaCubes().add(cub);       
      cub = new Cube(brick_texture , "brick");
      cub.X = -3.75f;
      cub.Y = 1.75f;
      cub.Z = 0.1f;
      main.gamePlayers.getListaCubes().add(cub);      
      cub = new Cube(brick_texture , "brick");
      cub.X = -3.25f;
      cub.Y = 1.75f;
      cub.Z = 0.1f;
      main.gamePlayers.getListaCubes().add(cub);     
      cub = new Cube(brick_texture , "brick");
      cub.X = -2.75f;
      cub.Y = 1.75f;
      cub.Z = 0.1f;
      main.gamePlayers.getListaCubes().add(cub);        
      cub = new Cube(brick_texture , "brick");
      cub.X = -2.25f;
      cub.Y = 1.75f;
      cub.Z = 0.1f;
      main.gamePlayers.getListaCubes().add(cub);         
      cub = new Cube(brick_texture , "brick");
      cub.X = -1.75f;
      cub.Y = 1.75f;
      cub.Z = 0.1f;
      main.gamePlayers.getListaCubes().add(cub);       
      cub = new Cube(brick_texture , "brick");
      cub.X = -1.25f;
      cub.Y = 1.75f;
      cub.Z = 0.1f;
      main.gamePlayers.getListaCubes().add(cub);          
      cub = new Cube(brick_texture , "brick");
      cub.X = -1.25f;
      cub.Y = 2.25f;
      cub.Z = 0.1f;
      main.gamePlayers.getListaCubes().add(cub);       
      cub = new Cube(brick_texture , "brick");
      cub.X = -1.75f;
      cub.Y = 2.25f;
      cub.Z = 0.1f;
      main.gamePlayers.getListaCubes().add(cub);      
      cub = new Cube(brick_texture , "brick");
      cub.X = -2.25f;
      cub.Y = 2.25f;
      cub.Z = 0.1f;
      main.gamePlayers.getListaCubes().add(cub);       
      cub = new Cube(brick_texture , "brick");
      cub.X = -2.75f;
      cub.Y = 2.25f;
      cub.Z = 0.1f;
      main.gamePlayers.getListaCubes().add(cub);        
      cub = new Cube(brick_texture , "brick");
      cub.X = -3.25f;
      cub.Y = 2.25f;
      cub.Z = 0.1f;
      main.gamePlayers.getListaCubes().add(cub);        
      cub = new Cube(brick_texture , "brick");
      cub.X = -3.75f;
      cub.Y = 2.25f;
      cub.Z = 0.1f;
      main.gamePlayers.getListaCubes().add(cub);        
      cub = new Cube(brick_texture , "brick");
      cub.X = -3.75f;
      cub.Y = 3.25f;
      cub.Z = 0.1f;
      main.gamePlayers.getListaCubes().add(cub);        
      cub = new Cube(brick_texture , "brick");
      cub.X = -3.25f;
      cub.Y = 3.25f;
      cub.Z = 0.1f;
      main.gamePlayers.getListaCubes().add(cub);         
      cub = new Cube(brick_texture , "brick");
      cub.X = -2.75f;
      cub.Y = 3.25f;
      cub.Z = 0.1f;
      main.gamePlayers.getListaCubes().add(cub);       
      cub = new Cube(brick_texture , "brick");
      cub.X = -2.25f;
      cub.Y = 3.25f;
      cub.Z = 0.1f;
      main.gamePlayers.getListaCubes().add(cub);        
      cub = new Cube(brick_texture , "brick");
      cub.X = -1.75f;
      cub.Y = 3.25f;
      cub.Z = 0.1f;
      main.gamePlayers.getListaCubes().add(cub);  
      cub = new Cube(brick_texture , "brick");
      cub.X = -1.25f;
      cub.Y = 3.25f;
      cub.Z = 0.1f;
      main.gamePlayers.getListaCubes().add(cub);      
      cub = new Cube(brick_texture , "brick");
      cub.X = -1.25f;
      cub.Y = 3.75f;
      cub.Z = 0.1f;
      main.gamePlayers.getListaCubes().add(cub);        
      cub = new Cube(brick_texture , "brick");
      cub.X = -1.75f;
      cub.Y = 3.75f;
      cub.Z = 0.1f;
      main.gamePlayers.getListaCubes().add(cub);       
      cub = new Cube(brick_texture , "brick");
      cub.X = -2.25f;
      cub.Y = 3.75f;
      cub.Z = 0.1f;
      main.gamePlayers.getListaCubes().add(cub);   
      cub = new Cube(brick_texture , "brick");
      cub.X = -2.75f;
      cub.Y = 3.75f;
      cub.Z = 0.1f;
      main.gamePlayers.getListaCubes().add(cub);       
      cub = new Cube(brick_texture , "brick");
      cub.X = -3.25f;
      cub.Y = 3.75f;
      cub.Z = 0.1f;
      main.gamePlayers.getListaCubes().add(cub);       
      cub = new Cube(brick_texture , "brick");
      cub.X = -3.75f;
      cub.Y = 3.75f;
      cub.Z = 0.1f;
      main.gamePlayers.getListaCubes().add(cub);         
    }   
}
